# Generated by Django 2.1.7 on 2019-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('RId', models.IntegerField(primary_key=True, serialize=False)),
                ('Response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniqueEntity',
            fields=[
                ('EId', models.IntegerField(primary_key=True, serialize=False)),
                ('Entity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniqueIntent',
            fields=[
                ('IId', models.IntegerField(primary_key=True, serialize=False)),
                ('Intent', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='responses',
            name='Entity_id',
            field=models.ForeignKey(db_column='Entity_id', default=0, on_delete='true', to='bot.UniqueEntity'),
        ),
        migrations.AddField(
            model_name='responses',
            name='Intent_id',
            field=models.ForeignKey(db_column='Intent_id', default=0, on_delete='true', to='bot.UniqueIntent'),
        ),
    ]
